server:
  port: 8099
  servlet:
    context-path: /security-springboot
spring:
  application:
    name: security-springboot

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/security-user?serverTimezone=Asia/Shanghai&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
