spring:
  application:
    name: gateway_server
  main:
    allow-bean-definition-overriding: true
server:
  port: 53010

logging:
  level:
    root: info
    org.springframework: info

zuul:
  retryable: true
  ignored-services: /*
  add-host-header: true
  sensitive-headers: /*
  # 转发路由
  routes:
    uaa-service:
      stripPrefix: false
      path: /uaa/**
    order-service:
      stripPrefix: false
      path: /order/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:53000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
feign:
  hystrix:
    # feign开启hystrix支持
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env
